server {
  listen 80;
  root /usr/share/nginx/html;
  autoindex on;
  charset utf-8;

  types {
    text/html        html htm;
    text/plain       txt;
    text/markdown    md;
    text/csv         csv;
    text/tab-separated-values tsv;
    application/json json;
    application/pdf  pdf;
    image/png        png;
    image/jpeg       jpg jpeg;
    application/vnd.openxmlformats-officedocument.spreadsheetml.sheet      xlsx;
    application/vnd.openxmlformats-officedocument.wordprocessingml.document docx;
  }

  default_type application/octet-stream;

  location ~ \.(csv|tsv|xlsx|docx)$ {
    add_header Content-Disposition "attachment";
  }
}
